### ISSUE TITLE
Trojan/Ransomware alert

### ISSUE THREAD

**Issue by nononymousse** [BlackRouter/PIDChecker#6]
Hi,

I don't think it's normal that your software as been reported as a Trojan/Ransomware

Can you investigate that please ?

Thanks

PS : [Here](https://www.virustotal.com/gui/file/99262ab91de9e9ddcab93e1f3f67cf356cbdb11bff959a05a51abbe1562f2366) is the link to the VirusTotal page with a screen of it

![image](https://user-images.githubusercontent.com/32956707/151423694-5190acac-3004-4317-b6c7-a2887134f16a.png)

**Comment by Quikfix73** [comment]
Many antivirus companies are flagging KMS (Key Management Services) or PID checking tools as either viruses or Trojans and these are all false positives since this PIDChecker program only checks keys and does not install any any cracked/pirated codes so what these antivirus companies are doing is classifying any type of KMS or PID checking tools as a virus which is NOT TRUE and a FALSE POSITIVE. 

Microsoft also does this and can read more about this here:

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=HackTool:Win64/AutoKMS

**Comment by nononymousse** [comment]
Thank you for your answer
